default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'techtv_development' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'techtv_test' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  username: <%= ENV['DATABASE_USER'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

production:
  <<: *default
  database: techtv_production
  username: techtv
  password: <%= ENV['DATABASE_PASSWORD'] %>
